apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ayushipwc123/hotel-booking-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:sre123@host.docker.internal:5432/hotel_booking"
            - name: SECRET_KEY
              value: "hotel_booking_secret_key_2026_change_this_to_a_long_random_value"
            - name: ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hotel-booking
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
